author: 'YC <yinso.chen@gmail.com>'
name: 'funclet'
description: 'A Simple NodeJS callback management library'
version: '0.1.1'
repository:
  type: 'git'
  url: 'git@github.com:yinso/funclet.git'
engines:
  node: '>= 0.8.4'
scripts:
  test: 'make test'
  prepublish: 'make'
main: './lib/funclet.js'
dependencies:
  'coffee-script': '=1.7.1'
  async: =0.9.0
  loglet: '>=0.1.1'
devDependencies:
  testlet: '>= 0.2.0'
  'coffee-bean': '>=0.1.0'
